# -*- coding: utf-8 -*-
"""Text_Summarization_using_SpaCy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2ulYI_zIqVyeoxesbPzEJ202-fSxyPQ
"""

#  we import SpaCy library and use its functions to perform nlp tasks.

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from heapq import nlargest
import pandas as pd
#  from string import punctuation

#  we imported stopwords and stored as dictionary.
def summarize(document1):
  stopwords = list(STOP_WORDS)

  #  we have loaded spacy's model as nlp i.e in english
  nlp = spacy.load('en')

  #  we stored a text data into the document1 as strin

  #  we loaded the text data in an nlp docx variable
  docx = nlp(document1)

  #print(docx)
  type(docx)


  #  Here we are creating a frequency table having frequenc counts corresponding to the word
  #  Docx is a list of sentences
  word_freq = {}

  for word in docx:
    if word.text not in stopwords:
      if word.text not in word_freq.keys():
        word_freq[word.text] = 1
      else :
        word_freq[word.text] +=1

  for word in word_freq.keys():
    word_freq[word] = word_freq[word]/max(word_freq.values())

  #  Sentence scores
  #   scoring every sentence on the basis of number of words
  sentence_list = [sentence for sentence in docx.sents ]

  #print(sentence_list)

  sentence_score = {}

  for sent in sentence_list:
    for word in sent:
      if word.text.lower() in word_freq.keys():
        if len(sent.text.split(' ')) < 30:
          if sent not in sentence_score.keys():
            sentence_score[sent] = word_freq[word.text.lower()]
          else :
            sentence_score[sent] += word_freq[word.text.lower()]

  #  This is the main function that dos]es final summariation . By changing the int value inside the function we can 
  #  change the degree of summarization

  summarized_sentence = nlargest(2,sentence_score,key = sentence_score.get)

  #  Now convert spacy text into normal text

  final_sentences = [w.text for w in summarized_sentence]

  #  Now join sentences

  summary = ' '.join(final_sentences)
  return summary

  #  from gensim.summarization import summarize # " editable lines"

  #  summarize(document1)